<Project Sdk="Dalamud.NET.Sdk/14.0.1">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Platforms>AnyCPU</Platforms>
		<Version>1.1.0.0</Version>
		<Authors>Infi, PunishedPineapple</Authors>
		<Copyright>Copyright © Infi, PunishedPineapple 2021-2025</Copyright>
		<PackageProjectUrl>https://github.com/Infiziert90/ReadyCheckHelper</PackageProjectUrl>
		<RepositoryUrl>https://github.com/Infiziert90/ReadyCheckHelper</RepositoryUrl>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<NoWarn>1701;1702;</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="ReadyCheckHelper.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="images\icon.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\**" DestinationFolder="Resources\$(RecursiveDir)" CopyToOutputDirectory="Always" />
	</ItemGroup>

	<PropertyGroup>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="CheapLoc">
			<Private>false</Private>
			<HintPath>$(DalamudLibPath)CheapLoc.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="images\" />
	</ItemGroup>
</Project>