<Project Sdk="Dalamud.NET.Sdk/15.0.0">
	<PropertyGroup>
		<Version>1.1.1.1</Version>
		<Authors>Infi, PunishedPineapple</Authors>
		<Copyright>Copyright © Infi, PunishedPineapple 2021-2025</Copyright>
		<PackageProjectUrl>https://github.com/Infiziert90/ReadyCheckHelper</PackageProjectUrl>
		<RepositoryUrl>https://github.com/Infiziert90/ReadyCheckHelper</RepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="ReadyCheckHelper.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="images\icon.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="images\" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\Language.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Language.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resources\Language.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Language.resx</DependentUpon>
	  </Compile>
	</ItemGroup>
</Project>