//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadyCheckHelper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReadyCheckHelper.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin works automatically; however, some text commands are supported.  Valid subcommands are {0}, {1}, and {2}.  Use \&quot;{3} &lt;subcommand&gt;\&quot; for more information on each subcommand..
        /// </summary>
        internal static string BasicHelpMessage {
            get {
                return ResourceManager.GetString("BasicHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        internal static string ButtonSaveandClose {
            get {
                return ResourceManager.GetString("ButtonSaveandClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the most recent ready check icons from the party/alliance lists..
        /// </summary>
        internal static string ClearSubcommandHelpMessage {
            get {
                return ResourceManager.GetString("ClearSubcommandHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance List Icon Offset.
        /// </summary>
        internal static string ConfigOptionAllianceListIconOffset {
            get {
                return ResourceManager.GetString("ConfigOptionAllianceListIconOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance List Icon Scale.
        /// </summary>
        internal static string ConfigOptionAllianceListIconScale {
            get {
                return ResourceManager.GetString("ConfigOptionAllianceListIconScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Log Channel:.
        /// </summary>
        internal static string ConfigOptionChatMessageChannel {
            get {
                return ResourceManager.GetString("ConfigOptionChatMessageChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After a certain number of seconds:.
        /// </summary>
        internal static string ConfigOptionClearPartyAllianceListafterXSeconds {
            get {
                return ResourceManager.GetString("ConfigOptionClearPartyAllianceListafterXSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear ready check from party/alliance lists:.
        /// </summary>
        internal static string ConfigOptionClearPartyAllianceListSettings {
            get {
                return ResourceManager.GetString("ConfigOptionClearPartyAllianceListSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upon entering combat..
        /// </summary>
        internal static string ConfigOptionClearPartyAllianceListuponEnteringCombat {
            get {
                return ResourceManager.GetString("ConfigOptionClearPartyAllianceListuponEnteringCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upon entering combat while in instance..
        /// </summary>
        internal static string ConfigOptionClearPartyAllianceListuponEnteringingCombatinInstance {
            get {
                return ResourceManager.GetString("ConfigOptionClearPartyAllianceListuponEnteringingCombatinInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upon entering instance..
        /// </summary>
        internal static string ConfigOptionClearPartyAllianceListuponEnteringInstance {
            get {
                return ResourceManager.GetString("ConfigOptionClearPartyAllianceListuponEnteringInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw ready check on party/alliance lists..
        /// </summary>
        internal static string ConfigOptionDrawonPartyAllianceLists {
            get {
                return ResourceManager.GetString("ConfigOptionDrawonPartyAllianceLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of names to show in chat:.
        /// </summary>
        internal static string ConfigOptionMaxNamesinChat {
            get {
                return ResourceManager.GetString("ConfigOptionMaxNamesinChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party List Icon Offset.
        /// </summary>
        internal static string ConfigOptionPartyListIconOffset {
            get {
                return ResourceManager.GetString("ConfigOptionPartyListIconOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party List Icon Scale.
        /// </summary>
        internal static string ConfigOptionPartyListIconScale {
            get {
                return ResourceManager.GetString("ConfigOptionPartyListIconScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the names of those not ready in the chat window..
        /// </summary>
        internal static string ConfigOptionPrintNamesofUnreadyinChat {
            get {
                return ResourceManager.GetString("ConfigOptionPrintNamesofUnreadyinChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party and Alliance List Icon Size/Offset:.
        /// </summary>
        internal static string ConfigSectionIconSizeOffset {
            get {
                return ResourceManager.GetString("ConfigSectionIconSizeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the settings window..
        /// </summary>
        internal static string ConfigSubcommandHelpMessage {
            get {
                return ResourceManager.GetString("ConfigSubcommandHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a debugging window containing party and ready check object data..
        /// </summary>
        internal static string DebugSubcommandHelpMessage {
            get {
                return ResourceManager.GetString("DebugSubcommandHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the channel in which this chat message is shown.  Leave this set to the default value ({0}) unless it causes problems with your chat configuration.  This only affects the unready players message; all other messages from this plugin respect your choice of chat channel in Dalamud settings..
        /// </summary>
        internal static string HelpChatMessageChannel {
            get {
                return ResourceManager.GetString("HelpChatMessageChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to this setting will not take effect until the next ready check concludes..
        /// </summary>
        internal static string HelpClearPartyAllianceListafterXSeconds {
            get {
                return ResourceManager.GetString("HelpClearPartyAllianceListafterXSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO NOT TOUCH THIS UNLESS YOU KNOW EXACTLY WHAT YOU&apos;RE DOING AND WHY; THE ABSOLUTE BEST CASE IS A PLUGIN CRASH..
        /// </summary>
        internal static string HelpDebugSetObjectAddressWarning {
            get {
                return ResourceManager.GetString("HelpDebugSetObjectAddressWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Ready: .
        /// </summary>
        internal static string NotReadyBase {
            get {
                return ResourceManager.GetString("NotReadyBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        internal static string NotReadyOther {
            get {
                return ResourceManager.GetString("NotReadyOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to others.
        /// </summary>
        internal static string NotReadyOthers {
            get {
                return ResourceManager.GetString("NotReadyOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ready check has yet occurred..
        /// </summary>
        internal static string PlaceholderNoReadyCheckResultsExist {
            get {
                return ResourceManager.GetString("PlaceholderNoReadyCheckResultsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} to open the the configuration window..
        /// </summary>
        internal static string PluginTextCommandDescription {
            get {
                return ResourceManager.GetString("PluginTextCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a window containing the results of the last ready check to occur..
        /// </summary>
        internal static string ResultsSubcommandHelpMessage {
            get {
                return ResourceManager.GetString("ResultsSubcommandHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready Check Helper Settings.
        /// </summary>
        internal static string WindowTitleConfig {
            get {
                return ResourceManager.GetString("WindowTitleConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Processed Ready Check Data.
        /// </summary>
        internal static string WindowTitleProcessedReadyCheckData {
            get {
                return ResourceManager.GetString("WindowTitleProcessedReadyCheckData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Raw Ready Check Data.
        /// </summary>
        internal static string WindowTitleRawReadyCheckData {
            get {
                return ResourceManager.GetString("WindowTitleRawReadyCheckData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready Check and Alliance Debug Data.
        /// </summary>
        internal static string WindowTitleReadyCheckandAllianceDebugData {
            get {
                return ResourceManager.GetString("WindowTitleReadyCheckandAllianceDebugData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Ready Check Results.
        /// </summary>
        internal static string WindowTitleReadyCheckResults {
            get {
                return ResourceManager.GetString("WindowTitleReadyCheckResults", resourceCulture);
            }
        }
    }
}
